name: "Version Cleaner Action"
description: "A GitHub Action for deleting packages with specific version from a GitHub repository"
inputs:
  github-repository:
    description: "The GitHub repository where snapshots will be deleted"
    required: true
  package-type:
    description: "The package type to delete (e.g., maven)"
    required: true
  version-tag:
    description: "The tag to use to identify version packages"
    required: true
  github-token:
    description: "The GitHub token to use for deleting packages. See required scopes in README.md"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-repository }}
    - ${{ inputs.package-type }}
    - ${{ inputs.version-tag }}
    - ${{ inputs.github-token }}