name: Kotlin Action

on:
  push:
    branches:
      - main
env:
  TOKEN: "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"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          chmod +x gradlew  # Ensure that the gradlew script is executable
          ./gradlew build  # Execute the Gradle build

      - name: Compile and Run Kotlin Script
        run: |
          java -cp build/classes/kotlin/main:build/resources/main src/main/kotlin/main.kt