name: Kotlin Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Compile and Run Kotlin Script
        run: |
          kotlinc src/main/kotlin/main.kt -include-runtime -d main.jar
          java -jar main.jar