name: Publish SNAPSHOT versions
on:
  workflow_dispatch:
  push:
    branches:
      - release/**
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Extract branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete previous SNAPSHOT packages
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build run
        env:
          PACKAGE_TYPE: maven
          VERSION_TAG: ${{ env.BRANCH_NAME }}-SNAPSHOT
          IS_VERSION_TAG_STRICT: true
          GITHUB_TOKEN: ${{ secrets.DELETE_PACKAGES_TOKEN }}

      - name: Publish new SNAPSHOT package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish -Pversion=${{ env.BRANCH_NAME }}-SNAPSHOT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
