name: Publish SNAPSHOT versions
on:
  workflow_dispatch:
  push:
    branches:
      - release/**
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Extract branch name
        id: extract_branch
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          VERSION=${BRANCH_NAME:8} # remove 'release/' prefix
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Delete previous SNAPSHOT packages
        shell: bash
        run: ./gradlew build run
        env:
          PACKAGE_TYPE: maven
          VERSION_TAG: ${{ env.VERSION }}-SNAPSHOT
          IS_VERSION_TAG_STRICT: true
          GITHUB_TOKEN: ${{ secrets.DELETE_PACKAGES_TOKEN }}

      - name: Publish new SNAPSHOT package
        shell: bash
        run: |
          VERSION = "${{ env.VERSION }}-SNAPSHOT"
          echo "VERSION=$VERSION"
          ./gradlew publish -Pversion=$VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}