name: Kotlin Action

on:
  create:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.8.0

      - name: Publish with Gradle
        run: |
          ./gradlew publish